// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// GetSeriesSeriesIDSemverReader is a Reader for the GetSeriesSeriesIDSemver structure.
type GetSeriesSeriesIDSemverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSeriesSeriesIDSemverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSeriesSeriesIDSemverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSeriesSeriesIDSemverBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetSeriesSeriesIDSemverUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetSeriesSeriesIDSemverForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSeriesSeriesIDSemverNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetSeriesSeriesIDSemverMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSeriesSeriesIDSemverInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetSeriesSeriesIDSemverDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSeriesSeriesIDSemverOK creates a GetSeriesSeriesIDSemverOK with default headers values
func NewGetSeriesSeriesIDSemverOK() *GetSeriesSeriesIDSemverOK {
	return &GetSeriesSeriesIDSemverOK{}
}

/* GetSeriesSeriesIDSemverOK describes a response with status code 200, with default header values.

All semver tagged versions available for a time series.

*/
type GetSeriesSeriesIDSemverOK struct {
	Payload []string
}

// IsSuccess returns true when this get series series Id semver o k response has a 2xx status code
func (o *GetSeriesSeriesIDSemverOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get series series Id semver o k response has a 3xx status code
func (o *GetSeriesSeriesIDSemverOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver o k response has a 4xx status code
func (o *GetSeriesSeriesIDSemverOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get series series Id semver o k response has a 5xx status code
func (o *GetSeriesSeriesIDSemverOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver o k response a status code equal to that given
func (o *GetSeriesSeriesIDSemverOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetSeriesSeriesIDSemverOK) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverOK  %+v", 200, o.Payload)
}

func (o *GetSeriesSeriesIDSemverOK) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverOK  %+v", 200, o.Payload)
}

func (o *GetSeriesSeriesIDSemverOK) GetPayload() []string {
	return o.Payload
}

func (o *GetSeriesSeriesIDSemverOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSeriesSeriesIDSemverBadRequest creates a GetSeriesSeriesIDSemverBadRequest with default headers values
func NewGetSeriesSeriesIDSemverBadRequest() *GetSeriesSeriesIDSemverBadRequest {
	return &GetSeriesSeriesIDSemverBadRequest{}
}

/* GetSeriesSeriesIDSemverBadRequest describes a response with status code 400, with default header values.

Client error in request. Input did not pass validations. See error details.

*/
type GetSeriesSeriesIDSemverBadRequest struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get series series Id semver bad request response has a 2xx status code
func (o *GetSeriesSeriesIDSemverBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver bad request response has a 3xx status code
func (o *GetSeriesSeriesIDSemverBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver bad request response has a 4xx status code
func (o *GetSeriesSeriesIDSemverBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get series series Id semver bad request response has a 5xx status code
func (o *GetSeriesSeriesIDSemverBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver bad request response a status code equal to that given
func (o *GetSeriesSeriesIDSemverBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetSeriesSeriesIDSemverBadRequest) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverBadRequest  %+v", 400, o.Payload)
}

func (o *GetSeriesSeriesIDSemverBadRequest) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverBadRequest  %+v", 400, o.Payload)
}

func (o *GetSeriesSeriesIDSemverBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetSeriesSeriesIDSemverBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSeriesSeriesIDSemverUnauthorized creates a GetSeriesSeriesIDSemverUnauthorized with default headers values
func NewGetSeriesSeriesIDSemverUnauthorized() *GetSeriesSeriesIDSemverUnauthorized {
	return &GetSeriesSeriesIDSemverUnauthorized{}
}

/* GetSeriesSeriesIDSemverUnauthorized describes a response with status code 401, with default header values.

Unauthorized access for a lack of authentication

*/
type GetSeriesSeriesIDSemverUnauthorized struct {
}

// IsSuccess returns true when this get series series Id semver unauthorized response has a 2xx status code
func (o *GetSeriesSeriesIDSemverUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver unauthorized response has a 3xx status code
func (o *GetSeriesSeriesIDSemverUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver unauthorized response has a 4xx status code
func (o *GetSeriesSeriesIDSemverUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get series series Id semver unauthorized response has a 5xx status code
func (o *GetSeriesSeriesIDSemverUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver unauthorized response a status code equal to that given
func (o *GetSeriesSeriesIDSemverUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetSeriesSeriesIDSemverUnauthorized) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverUnauthorized ", 401)
}

func (o *GetSeriesSeriesIDSemverUnauthorized) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverUnauthorized ", 401)
}

func (o *GetSeriesSeriesIDSemverUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSeriesSeriesIDSemverForbidden creates a GetSeriesSeriesIDSemverForbidden with default headers values
func NewGetSeriesSeriesIDSemverForbidden() *GetSeriesSeriesIDSemverForbidden {
	return &GetSeriesSeriesIDSemverForbidden{}
}

/* GetSeriesSeriesIDSemverForbidden describes a response with status code 403, with default header values.

Forbidden access for a lack of sufficient privileges

*/
type GetSeriesSeriesIDSemverForbidden struct {
}

// IsSuccess returns true when this get series series Id semver forbidden response has a 2xx status code
func (o *GetSeriesSeriesIDSemverForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver forbidden response has a 3xx status code
func (o *GetSeriesSeriesIDSemverForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver forbidden response has a 4xx status code
func (o *GetSeriesSeriesIDSemverForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get series series Id semver forbidden response has a 5xx status code
func (o *GetSeriesSeriesIDSemverForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver forbidden response a status code equal to that given
func (o *GetSeriesSeriesIDSemverForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetSeriesSeriesIDSemverForbidden) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverForbidden ", 403)
}

func (o *GetSeriesSeriesIDSemverForbidden) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverForbidden ", 403)
}

func (o *GetSeriesSeriesIDSemverForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSeriesSeriesIDSemverNotFound creates a GetSeriesSeriesIDSemverNotFound with default headers values
func NewGetSeriesSeriesIDSemverNotFound() *GetSeriesSeriesIDSemverNotFound {
	return &GetSeriesSeriesIDSemverNotFound{}
}

/* GetSeriesSeriesIDSemverNotFound describes a response with status code 404, with default header values.

Resource not found. The object requested does not exist or is not visible to the user.

*/
type GetSeriesSeriesIDSemverNotFound struct {
}

// IsSuccess returns true when this get series series Id semver not found response has a 2xx status code
func (o *GetSeriesSeriesIDSemverNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver not found response has a 3xx status code
func (o *GetSeriesSeriesIDSemverNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver not found response has a 4xx status code
func (o *GetSeriesSeriesIDSemverNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get series series Id semver not found response has a 5xx status code
func (o *GetSeriesSeriesIDSemverNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver not found response a status code equal to that given
func (o *GetSeriesSeriesIDSemverNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetSeriesSeriesIDSemverNotFound) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverNotFound ", 404)
}

func (o *GetSeriesSeriesIDSemverNotFound) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverNotFound ", 404)
}

func (o *GetSeriesSeriesIDSemverNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSeriesSeriesIDSemverMethodNotAllowed creates a GetSeriesSeriesIDSemverMethodNotAllowed with default headers values
func NewGetSeriesSeriesIDSemverMethodNotAllowed() *GetSeriesSeriesIDSemverMethodNotAllowed {
	return &GetSeriesSeriesIDSemverMethodNotAllowed{}
}

/* GetSeriesSeriesIDSemverMethodNotAllowed describes a response with status code 405, with default header values.

MethodNotAllowed

*/
type GetSeriesSeriesIDSemverMethodNotAllowed struct {
}

// IsSuccess returns true when this get series series Id semver method not allowed response has a 2xx status code
func (o *GetSeriesSeriesIDSemverMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver method not allowed response has a 3xx status code
func (o *GetSeriesSeriesIDSemverMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver method not allowed response has a 4xx status code
func (o *GetSeriesSeriesIDSemverMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get series series Id semver method not allowed response has a 5xx status code
func (o *GetSeriesSeriesIDSemverMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get series series Id semver method not allowed response a status code equal to that given
func (o *GetSeriesSeriesIDSemverMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *GetSeriesSeriesIDSemverMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverMethodNotAllowed ", 405)
}

func (o *GetSeriesSeriesIDSemverMethodNotAllowed) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverMethodNotAllowed ", 405)
}

func (o *GetSeriesSeriesIDSemverMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSeriesSeriesIDSemverInternalServerError creates a GetSeriesSeriesIDSemverInternalServerError with default headers values
func NewGetSeriesSeriesIDSemverInternalServerError() *GetSeriesSeriesIDSemverInternalServerError {
	return &GetSeriesSeriesIDSemverInternalServerError{}
}

/* GetSeriesSeriesIDSemverInternalServerError describes a response with status code 500, with default header values.

An internal error has occured. See error details.

*/
type GetSeriesSeriesIDSemverInternalServerError struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get series series Id semver internal server error response has a 2xx status code
func (o *GetSeriesSeriesIDSemverInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get series series Id semver internal server error response has a 3xx status code
func (o *GetSeriesSeriesIDSemverInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get series series Id semver internal server error response has a 4xx status code
func (o *GetSeriesSeriesIDSemverInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get series series Id semver internal server error response has a 5xx status code
func (o *GetSeriesSeriesIDSemverInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get series series Id semver internal server error response a status code equal to that given
func (o *GetSeriesSeriesIDSemverInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetSeriesSeriesIDSemverInternalServerError) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSeriesSeriesIDSemverInternalServerError) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] getSeriesSeriesIdSemverInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSeriesSeriesIDSemverInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetSeriesSeriesIDSemverInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSeriesSeriesIDSemverDefault creates a GetSeriesSeriesIDSemverDefault with default headers values
func NewGetSeriesSeriesIDSemverDefault(code int) *GetSeriesSeriesIDSemverDefault {
	return &GetSeriesSeriesIDSemverDefault{
		_statusCode: code,
	}
}

/* GetSeriesSeriesIDSemverDefault describes a response with status code -1, with default header values.

Other error. See error details.

*/
type GetSeriesSeriesIDSemverDefault struct {
	_statusCode int

	Payload *models.APIError
}

// Code gets the status code for the get series series ID semver default response
func (o *GetSeriesSeriesIDSemverDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get series series ID semver default response has a 2xx status code
func (o *GetSeriesSeriesIDSemverDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get series series ID semver default response has a 3xx status code
func (o *GetSeriesSeriesIDSemverDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get series series ID semver default response has a 4xx status code
func (o *GetSeriesSeriesIDSemverDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get series series ID semver default response has a 5xx status code
func (o *GetSeriesSeriesIDSemverDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get series series ID semver default response a status code equal to that given
func (o *GetSeriesSeriesIDSemverDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetSeriesSeriesIDSemverDefault) Error() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] GetSeriesSeriesIDSemver default  %+v", o._statusCode, o.Payload)
}

func (o *GetSeriesSeriesIDSemverDefault) String() string {
	return fmt.Sprintf("[GET /series/{seriesId}/semver][%d] GetSeriesSeriesIDSemver default  %+v", o._statusCode, o.Payload)
}

func (o *GetSeriesSeriesIDSemverDefault) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetSeriesSeriesIDSemverDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
