// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSeriesSeriesIDParams creates a new DeleteSeriesSeriesIDParams object
//
// There are no default values defined in the spec.
func NewDeleteSeriesSeriesIDParams() DeleteSeriesSeriesIDParams {

	return DeleteSeriesSeriesIDParams{}
}

// DeleteSeriesSeriesIDParams contains all the bound params for the delete series series ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteSeriesSeriesID
type DeleteSeriesSeriesIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The unique ID of a time series.
	  Required: true
	  In: path
	*/
	SeriesID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteSeriesSeriesIDParams() beforehand.
func (o *DeleteSeriesSeriesIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSeriesID, rhkSeriesID, _ := route.Params.GetOK("seriesId")
	if err := o.bindSeriesID(rSeriesID, rhkSeriesID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSeriesID binds and validates parameter SeriesID from path.
func (o *DeleteSeriesSeriesIDParams) bindSeriesID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("seriesId", "path", "int64", raw)
	}
	o.SeriesID = value

	return nil
}
