// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// GetSeriesSeriesIDSemverSemverOKCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverOK
const GetSeriesSeriesIDSemverSemverOKCode int = 200

/*GetSeriesSeriesIDSemverSemverOK Versioned time series for a given semver tag.


swagger:response getSeriesSeriesIdSemverSemverOK
*/
type GetSeriesSeriesIDSemverSemverOK struct {

	/*
	  In: Body
	*/
	Payload *models.VersionedSeries `json:"body,omitempty"`
}

// NewGetSeriesSeriesIDSemverSemverOK creates GetSeriesSeriesIDSemverSemverOK with default headers values
func NewGetSeriesSeriesIDSemverSemverOK() *GetSeriesSeriesIDSemverSemverOK {

	return &GetSeriesSeriesIDSemverSemverOK{}
}

// WithPayload adds the payload to the get series series Id semver semver o k response
func (o *GetSeriesSeriesIDSemverSemverOK) WithPayload(payload *models.VersionedSeries) *GetSeriesSeriesIDSemverSemverOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get series series Id semver semver o k response
func (o *GetSeriesSeriesIDSemverSemverOK) SetPayload(payload *models.VersionedSeries) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSeriesSeriesIDSemverSemverOK) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverBadRequestCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverBadRequest
const GetSeriesSeriesIDSemverSemverBadRequestCode int = 400

/*GetSeriesSeriesIDSemverSemverBadRequest Client error in request. Input did not pass validations. See error details.


swagger:response getSeriesSeriesIdSemverSemverBadRequest
*/
type GetSeriesSeriesIDSemverSemverBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetSeriesSeriesIDSemverSemverBadRequest creates GetSeriesSeriesIDSemverSemverBadRequest with default headers values
func NewGetSeriesSeriesIDSemverSemverBadRequest() *GetSeriesSeriesIDSemverSemverBadRequest {

	return &GetSeriesSeriesIDSemverSemverBadRequest{}
}

// WithPayload adds the payload to the get series series Id semver semver bad request response
func (o *GetSeriesSeriesIDSemverSemverBadRequest) WithPayload(payload *models.APIError) *GetSeriesSeriesIDSemverSemverBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get series series Id semver semver bad request response
func (o *GetSeriesSeriesIDSemverSemverBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSeriesSeriesIDSemverSemverBadRequest) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverUnauthorizedCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverUnauthorized
const GetSeriesSeriesIDSemverSemverUnauthorizedCode int = 401

/*GetSeriesSeriesIDSemverSemverUnauthorized Unauthorized access for a lack of authentication


swagger:response getSeriesSeriesIdSemverSemverUnauthorized
*/
type GetSeriesSeriesIDSemverSemverUnauthorized struct {
}

// NewGetSeriesSeriesIDSemverSemverUnauthorized creates GetSeriesSeriesIDSemverSemverUnauthorized with default headers values
func NewGetSeriesSeriesIDSemverSemverUnauthorized() *GetSeriesSeriesIDSemverSemverUnauthorized {

	return &GetSeriesSeriesIDSemverSemverUnauthorized{}
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *GetSeriesSeriesIDSemverSemverUnauthorized) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverForbiddenCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverForbidden
const GetSeriesSeriesIDSemverSemverForbiddenCode int = 403

/*GetSeriesSeriesIDSemverSemverForbidden Forbidden access for a lack of sufficient privileges


swagger:response getSeriesSeriesIdSemverSemverForbidden
*/
type GetSeriesSeriesIDSemverSemverForbidden struct {
}

// NewGetSeriesSeriesIDSemverSemverForbidden creates GetSeriesSeriesIDSemverSemverForbidden with default headers values
func NewGetSeriesSeriesIDSemverSemverForbidden() *GetSeriesSeriesIDSemverSemverForbidden {

	return &GetSeriesSeriesIDSemverSemverForbidden{}
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *GetSeriesSeriesIDSemverSemverForbidden) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverNotFoundCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverNotFound
const GetSeriesSeriesIDSemverSemverNotFoundCode int = 404

/*GetSeriesSeriesIDSemverSemverNotFound Resource not found. The object requested does not exist or is not visible to the user.


swagger:response getSeriesSeriesIdSemverSemverNotFound
*/
type GetSeriesSeriesIDSemverSemverNotFound struct {
}

// NewGetSeriesSeriesIDSemverSemverNotFound creates GetSeriesSeriesIDSemverSemverNotFound with default headers values
func NewGetSeriesSeriesIDSemverSemverNotFound() *GetSeriesSeriesIDSemverSemverNotFound {

	return &GetSeriesSeriesIDSemverSemverNotFound{}
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

func (o *GetSeriesSeriesIDSemverSemverNotFound) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverMethodNotAllowedCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverMethodNotAllowed
const GetSeriesSeriesIDSemverSemverMethodNotAllowedCode int = 405

/*GetSeriesSeriesIDSemverSemverMethodNotAllowed MethodNotAllowed


swagger:response getSeriesSeriesIdSemverSemverMethodNotAllowed
*/
type GetSeriesSeriesIDSemverSemverMethodNotAllowed struct {
}

// NewGetSeriesSeriesIDSemverSemverMethodNotAllowed creates GetSeriesSeriesIDSemverSemverMethodNotAllowed with default headers values
func NewGetSeriesSeriesIDSemverSemverMethodNotAllowed() *GetSeriesSeriesIDSemverSemverMethodNotAllowed {

	return &GetSeriesSeriesIDSemverSemverMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

func (o *GetSeriesSeriesIDSemverSemverMethodNotAllowed) GetSeriesSeriesIDSemverSemverResponder() {}

// GetSeriesSeriesIDSemverSemverInternalServerErrorCode is the HTTP code returned for type GetSeriesSeriesIDSemverSemverInternalServerError
const GetSeriesSeriesIDSemverSemverInternalServerErrorCode int = 500

/*GetSeriesSeriesIDSemverSemverInternalServerError An internal error has occured. See error details.


swagger:response getSeriesSeriesIdSemverSemverInternalServerError
*/
type GetSeriesSeriesIDSemverSemverInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetSeriesSeriesIDSemverSemverInternalServerError creates GetSeriesSeriesIDSemverSemverInternalServerError with default headers values
func NewGetSeriesSeriesIDSemverSemverInternalServerError() *GetSeriesSeriesIDSemverSemverInternalServerError {

	return &GetSeriesSeriesIDSemverSemverInternalServerError{}
}

// WithPayload adds the payload to the get series series Id semver semver internal server error response
func (o *GetSeriesSeriesIDSemverSemverInternalServerError) WithPayload(payload *models.APIError) *GetSeriesSeriesIDSemverSemverInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get series series Id semver semver internal server error response
func (o *GetSeriesSeriesIDSemverSemverInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSeriesSeriesIDSemverSemverInternalServerError) GetSeriesSeriesIDSemverSemverResponder() {}

/*GetSeriesSeriesIDSemverSemverDefault Other error. See error details.


swagger:response getSeriesSeriesIdSemverSemverDefault
*/
type GetSeriesSeriesIDSemverSemverDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetSeriesSeriesIDSemverSemverDefault creates GetSeriesSeriesIDSemverSemverDefault with default headers values
func NewGetSeriesSeriesIDSemverSemverDefault(code int) *GetSeriesSeriesIDSemverSemverDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSeriesSeriesIDSemverSemverDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get series series ID semver semver default response
func (o *GetSeriesSeriesIDSemverSemverDefault) WithStatusCode(code int) *GetSeriesSeriesIDSemverSemverDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get series series ID semver semver default response
func (o *GetSeriesSeriesIDSemverSemverDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get series series ID semver semver default response
func (o *GetSeriesSeriesIDSemverSemverDefault) WithPayload(payload *models.APIError) *GetSeriesSeriesIDSemverSemverDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get series series ID semver semver default response
func (o *GetSeriesSeriesIDSemverSemverDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSeriesSeriesIDSemverSemverDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSeriesSeriesIDSemverSemverDefault) GetSeriesSeriesIDSemverSemverResponder() {}

type GetSeriesSeriesIDSemverSemverNotImplementedResponder struct {
	middleware.Responder
}

func (*GetSeriesSeriesIDSemverSemverNotImplementedResponder) GetSeriesSeriesIDSemverSemverResponder() {
}

func GetSeriesSeriesIDSemverSemverNotImplemented() GetSeriesSeriesIDSemverSemverResponder {
	return &GetSeriesSeriesIDSemverSemverNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetSeriesSeriesIDSemverSemver has not yet been implemented",
		),
	}
}

type GetSeriesSeriesIDSemverSemverResponder interface {
	middleware.Responder
	GetSeriesSeriesIDSemverSemverResponder()
}
