// Code generated by go-swagger; DO NOT EDIT.

package classes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetClassesClassIDParams creates a new GetClassesClassIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClassesClassIDParams() *GetClassesClassIDParams {
	return &GetClassesClassIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClassesClassIDParamsWithTimeout creates a new GetClassesClassIDParams object
// with the ability to set a timeout on a request.
func NewGetClassesClassIDParamsWithTimeout(timeout time.Duration) *GetClassesClassIDParams {
	return &GetClassesClassIDParams{
		timeout: timeout,
	}
}

// NewGetClassesClassIDParamsWithContext creates a new GetClassesClassIDParams object
// with the ability to set a context for a request.
func NewGetClassesClassIDParamsWithContext(ctx context.Context) *GetClassesClassIDParams {
	return &GetClassesClassIDParams{
		Context: ctx,
	}
}

// NewGetClassesClassIDParamsWithHTTPClient creates a new GetClassesClassIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClassesClassIDParamsWithHTTPClient(client *http.Client) *GetClassesClassIDParams {
	return &GetClassesClassIDParams{
		HTTPClient: client,
	}
}

/* GetClassesClassIDParams contains all the parameters to send to the API endpoint
   for the get classes class ID operation.

   Typically these are written to a http.Request.
*/
type GetClassesClassIDParams struct {

	/* Audit.

	   When audit is specified, the response will also contain the audit trail field.

	*/
	Audit *bool

	/* Brief.

	   When brief is specified, the response will only contain essential data and strip long descriptions.

	*/
	Brief *bool

	/* ClassID.

	     The internal name of a nomenclature class.

	Valid classes are:
	  * constant: mathematical and physical constants
	  * mdimension: base measured dimensions
	  * mdomain: domains that pertain to measurements
	  * measurement: physical and economic measurements
	  * multiplier: unit multipliers aka prefixes (e.g. k,M,G...)
	  * munit: measurement units
	  * musystem: systems of measurement units
	  * ostatus: owner statuses
	  * owner: series owner
	  * period: time series periods (e.g. monthly, yearly...)
	  * role: series owner role
	  * source: data sources
	  * status: series and versions statuses
	  * theme: climate themes
	  * zone: geographical zones
	  * ztype: zone types

	*/
	ClassID string

	/* Deep.

	   When deep is specified, the response will contain a deep representation of the object, rather than just a shallow description.

	*/
	Deep *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get classes class ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClassesClassIDParams) WithDefaults() *GetClassesClassIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get classes class ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClassesClassIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get classes class ID params
func (o *GetClassesClassIDParams) WithTimeout(timeout time.Duration) *GetClassesClassIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get classes class ID params
func (o *GetClassesClassIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get classes class ID params
func (o *GetClassesClassIDParams) WithContext(ctx context.Context) *GetClassesClassIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get classes class ID params
func (o *GetClassesClassIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get classes class ID params
func (o *GetClassesClassIDParams) WithHTTPClient(client *http.Client) *GetClassesClassIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get classes class ID params
func (o *GetClassesClassIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAudit adds the audit to the get classes class ID params
func (o *GetClassesClassIDParams) WithAudit(audit *bool) *GetClassesClassIDParams {
	o.SetAudit(audit)
	return o
}

// SetAudit adds the audit to the get classes class ID params
func (o *GetClassesClassIDParams) SetAudit(audit *bool) {
	o.Audit = audit
}

// WithBrief adds the brief to the get classes class ID params
func (o *GetClassesClassIDParams) WithBrief(brief *bool) *GetClassesClassIDParams {
	o.SetBrief(brief)
	return o
}

// SetBrief adds the brief to the get classes class ID params
func (o *GetClassesClassIDParams) SetBrief(brief *bool) {
	o.Brief = brief
}

// WithClassID adds the classID to the get classes class ID params
func (o *GetClassesClassIDParams) WithClassID(classID string) *GetClassesClassIDParams {
	o.SetClassID(classID)
	return o
}

// SetClassID adds the classId to the get classes class ID params
func (o *GetClassesClassIDParams) SetClassID(classID string) {
	o.ClassID = classID
}

// WithDeep adds the deep to the get classes class ID params
func (o *GetClassesClassIDParams) WithDeep(deep *bool) *GetClassesClassIDParams {
	o.SetDeep(deep)
	return o
}

// SetDeep adds the deep to the get classes class ID params
func (o *GetClassesClassIDParams) SetDeep(deep *bool) {
	o.Deep = deep
}

// WriteToRequest writes these params to a swagger request
func (o *GetClassesClassIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Audit != nil {

		// query param audit
		var qrAudit bool

		if o.Audit != nil {
			qrAudit = *o.Audit
		}
		qAudit := swag.FormatBool(qrAudit)
		if qAudit != "" {

			if err := r.SetQueryParam("audit", qAudit); err != nil {
				return err
			}
		}
	}

	if o.Brief != nil {

		// query param brief
		var qrBrief bool

		if o.Brief != nil {
			qrBrief = *o.Brief
		}
		qBrief := swag.FormatBool(qrBrief)
		if qBrief != "" {

			if err := r.SetQueryParam("brief", qBrief); err != nil {
				return err
			}
		}
	}

	// path param classId
	if err := r.SetPathParam("classId", o.ClassID); err != nil {
		return err
	}

	if o.Deep != nil {

		// query param deep
		var qrDeep bool

		if o.Deep != nil {
			qrDeep = *o.Deep
		}
		qDeep := swag.FormatBool(qrDeep)
		if qDeep != "" {

			if err := r.SetQueryParam("deep", qDeep); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
