// Code generated by go-swagger; DO NOT EDIT.

package conversions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetConversionFromUnitToUnitURL generates an URL for the get conversion from unit to unit operation
type GetConversionFromUnitToUnitURL struct {
	FromUnit string
	ToUnit   string

	Audit *bool
	Brief *bool
	Deep  *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetConversionFromUnitToUnitURL) WithBasePath(bp string) *GetConversionFromUnitToUnitURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetConversionFromUnitToUnitURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetConversionFromUnitToUnitURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/conversion/{fromUnit}/{toUnit}"

	fromUnit := o.FromUnit
	if fromUnit != "" {
		_path = strings.Replace(_path, "{fromUnit}", fromUnit, -1)
	} else {
		return nil, errors.New("fromUnit is required on GetConversionFromUnitToUnitURL")
	}

	toUnit := o.ToUnit
	if toUnit != "" {
		_path = strings.Replace(_path, "{toUnit}", toUnit, -1)
	} else {
		return nil, errors.New("toUnit is required on GetConversionFromUnitToUnitURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var auditQ string
	if o.Audit != nil {
		auditQ = swag.FormatBool(*o.Audit)
	}
	if auditQ != "" {
		qs.Set("audit", auditQ)
	}

	var briefQ string
	if o.Brief != nil {
		briefQ = swag.FormatBool(*o.Brief)
	}
	if briefQ != "" {
		qs.Set("brief", briefQ)
	}

	var deepQ string
	if o.Deep != nil {
		deepQ = swag.FormatBool(*o.Deep)
	}
	if deepQ != "" {
		qs.Set("deep", deepQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetConversionFromUnitToUnitURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetConversionFromUnitToUnitURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetConversionFromUnitToUnitURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetConversionFromUnitToUnitURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetConversionFromUnitToUnitURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetConversionFromUnitToUnitURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
