// Code generated by go-swagger; DO NOT EDIT.

package conversions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// PostConversionsFromUnitToUnitCreatedCode is the HTTP code returned for type PostConversionsFromUnitToUnitCreated
const PostConversionsFromUnitToUnitCreatedCode int = 201

/*PostConversionsFromUnitToUnitCreated Unit conversion added.


swagger:response postConversionsFromUnitToUnitCreated
*/
type PostConversionsFromUnitToUnitCreated struct {
	/*The URI of the newly create resource.


	 */
	Location strfmt.URI `json:"Location"`
}

// NewPostConversionsFromUnitToUnitCreated creates PostConversionsFromUnitToUnitCreated with default headers values
func NewPostConversionsFromUnitToUnitCreated() *PostConversionsFromUnitToUnitCreated {

	return &PostConversionsFromUnitToUnitCreated{}
}

// WithLocation adds the location to the post conversions from unit to unit created response
func (o *PostConversionsFromUnitToUnitCreated) WithLocation(location strfmt.URI) *PostConversionsFromUnitToUnitCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the post conversions from unit to unit created response
func (o *PostConversionsFromUnitToUnitCreated) SetLocation(location strfmt.URI) {
	o.Location = location
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location.String()
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

func (o *PostConversionsFromUnitToUnitCreated) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitBadRequestCode is the HTTP code returned for type PostConversionsFromUnitToUnitBadRequest
const PostConversionsFromUnitToUnitBadRequestCode int = 400

/*PostConversionsFromUnitToUnitBadRequest Client error in request. Input did not pass validations. See error details.


swagger:response postConversionsFromUnitToUnitBadRequest
*/
type PostConversionsFromUnitToUnitBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostConversionsFromUnitToUnitBadRequest creates PostConversionsFromUnitToUnitBadRequest with default headers values
func NewPostConversionsFromUnitToUnitBadRequest() *PostConversionsFromUnitToUnitBadRequest {

	return &PostConversionsFromUnitToUnitBadRequest{}
}

// WithPayload adds the payload to the post conversions from unit to unit bad request response
func (o *PostConversionsFromUnitToUnitBadRequest) WithPayload(payload *models.APIError) *PostConversionsFromUnitToUnitBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post conversions from unit to unit bad request response
func (o *PostConversionsFromUnitToUnitBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *PostConversionsFromUnitToUnitBadRequest) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitUnauthorizedCode is the HTTP code returned for type PostConversionsFromUnitToUnitUnauthorized
const PostConversionsFromUnitToUnitUnauthorizedCode int = 401

/*PostConversionsFromUnitToUnitUnauthorized Unauthorized access for a lack of authentication


swagger:response postConversionsFromUnitToUnitUnauthorized
*/
type PostConversionsFromUnitToUnitUnauthorized struct {
}

// NewPostConversionsFromUnitToUnitUnauthorized creates PostConversionsFromUnitToUnitUnauthorized with default headers values
func NewPostConversionsFromUnitToUnitUnauthorized() *PostConversionsFromUnitToUnitUnauthorized {

	return &PostConversionsFromUnitToUnitUnauthorized{}
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

func (o *PostConversionsFromUnitToUnitUnauthorized) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitForbiddenCode is the HTTP code returned for type PostConversionsFromUnitToUnitForbidden
const PostConversionsFromUnitToUnitForbiddenCode int = 403

/*PostConversionsFromUnitToUnitForbidden Forbidden access for a lack of sufficient privileges


swagger:response postConversionsFromUnitToUnitForbidden
*/
type PostConversionsFromUnitToUnitForbidden struct {
}

// NewPostConversionsFromUnitToUnitForbidden creates PostConversionsFromUnitToUnitForbidden with default headers values
func NewPostConversionsFromUnitToUnitForbidden() *PostConversionsFromUnitToUnitForbidden {

	return &PostConversionsFromUnitToUnitForbidden{}
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

func (o *PostConversionsFromUnitToUnitForbidden) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitNotFoundCode is the HTTP code returned for type PostConversionsFromUnitToUnitNotFound
const PostConversionsFromUnitToUnitNotFoundCode int = 404

/*PostConversionsFromUnitToUnitNotFound Resource not found. The object requested does not exist or is not visible to the user.


swagger:response postConversionsFromUnitToUnitNotFound
*/
type PostConversionsFromUnitToUnitNotFound struct {
}

// NewPostConversionsFromUnitToUnitNotFound creates PostConversionsFromUnitToUnitNotFound with default headers values
func NewPostConversionsFromUnitToUnitNotFound() *PostConversionsFromUnitToUnitNotFound {

	return &PostConversionsFromUnitToUnitNotFound{}
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

func (o *PostConversionsFromUnitToUnitNotFound) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitMethodNotAllowedCode is the HTTP code returned for type PostConversionsFromUnitToUnitMethodNotAllowed
const PostConversionsFromUnitToUnitMethodNotAllowedCode int = 405

/*PostConversionsFromUnitToUnitMethodNotAllowed MethodNotAllowed


swagger:response postConversionsFromUnitToUnitMethodNotAllowed
*/
type PostConversionsFromUnitToUnitMethodNotAllowed struct {
}

// NewPostConversionsFromUnitToUnitMethodNotAllowed creates PostConversionsFromUnitToUnitMethodNotAllowed with default headers values
func NewPostConversionsFromUnitToUnitMethodNotAllowed() *PostConversionsFromUnitToUnitMethodNotAllowed {

	return &PostConversionsFromUnitToUnitMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

func (o *PostConversionsFromUnitToUnitMethodNotAllowed) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitConflictCode is the HTTP code returned for type PostConversionsFromUnitToUnitConflict
const PostConversionsFromUnitToUnitConflictCode int = 409

/*PostConversionsFromUnitToUnitConflict Resource already exists. An object creation was requested, but this object was already existing.


swagger:response postConversionsFromUnitToUnitConflict
*/
type PostConversionsFromUnitToUnitConflict struct {
}

// NewPostConversionsFromUnitToUnitConflict creates PostConversionsFromUnitToUnitConflict with default headers values
func NewPostConversionsFromUnitToUnitConflict() *PostConversionsFromUnitToUnitConflict {

	return &PostConversionsFromUnitToUnitConflict{}
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

func (o *PostConversionsFromUnitToUnitConflict) PostConversionsFromUnitToUnitResponder() {}

// PostConversionsFromUnitToUnitInternalServerErrorCode is the HTTP code returned for type PostConversionsFromUnitToUnitInternalServerError
const PostConversionsFromUnitToUnitInternalServerErrorCode int = 500

/*PostConversionsFromUnitToUnitInternalServerError An internal error has occured. See error details.


swagger:response postConversionsFromUnitToUnitInternalServerError
*/
type PostConversionsFromUnitToUnitInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostConversionsFromUnitToUnitInternalServerError creates PostConversionsFromUnitToUnitInternalServerError with default headers values
func NewPostConversionsFromUnitToUnitInternalServerError() *PostConversionsFromUnitToUnitInternalServerError {

	return &PostConversionsFromUnitToUnitInternalServerError{}
}

// WithPayload adds the payload to the post conversions from unit to unit internal server error response
func (o *PostConversionsFromUnitToUnitInternalServerError) WithPayload(payload *models.APIError) *PostConversionsFromUnitToUnitInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post conversions from unit to unit internal server error response
func (o *PostConversionsFromUnitToUnitInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *PostConversionsFromUnitToUnitInternalServerError) PostConversionsFromUnitToUnitResponder() {}

/*PostConversionsFromUnitToUnitDefault Other error. See error details.


swagger:response postConversionsFromUnitToUnitDefault
*/
type PostConversionsFromUnitToUnitDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostConversionsFromUnitToUnitDefault creates PostConversionsFromUnitToUnitDefault with default headers values
func NewPostConversionsFromUnitToUnitDefault(code int) *PostConversionsFromUnitToUnitDefault {
	if code <= 0 {
		code = 500
	}

	return &PostConversionsFromUnitToUnitDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post conversions from unit to unit default response
func (o *PostConversionsFromUnitToUnitDefault) WithStatusCode(code int) *PostConversionsFromUnitToUnitDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post conversions from unit to unit default response
func (o *PostConversionsFromUnitToUnitDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post conversions from unit to unit default response
func (o *PostConversionsFromUnitToUnitDefault) WithPayload(payload *models.APIError) *PostConversionsFromUnitToUnitDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post conversions from unit to unit default response
func (o *PostConversionsFromUnitToUnitDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConversionsFromUnitToUnitDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *PostConversionsFromUnitToUnitDefault) PostConversionsFromUnitToUnitResponder() {}

type PostConversionsFromUnitToUnitNotImplementedResponder struct {
	middleware.Responder
}

func (*PostConversionsFromUnitToUnitNotImplementedResponder) PostConversionsFromUnitToUnitResponder() {
}

func PostConversionsFromUnitToUnitNotImplemented() PostConversionsFromUnitToUnitResponder {
	return &PostConversionsFromUnitToUnitNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.PostConversionsFromUnitToUnit has not yet been implemented",
		),
	}
}

type PostConversionsFromUnitToUnitResponder interface {
	middleware.Responder
	PostConversionsFromUnitToUnitResponder()
}
