// Code generated by go-swagger; DO NOT EDIT.

package conversions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/fredbi/climate-timeseries/pkg/auth"
)

// PostConversionsFromUnitToUnitHandlerFunc turns a function with the right signature into a post conversions from unit to unit handler
type PostConversionsFromUnitToUnitHandlerFunc func(PostConversionsFromUnitToUnitParams, auth.Principal) PostConversionsFromUnitToUnitResponder

// Handle executing the request and returning a response
func (fn PostConversionsFromUnitToUnitHandlerFunc) Handle(params PostConversionsFromUnitToUnitParams, principal auth.Principal) PostConversionsFromUnitToUnitResponder {
	return fn(params, principal)
}

// PostConversionsFromUnitToUnitHandler interface for that can handle valid post conversions from unit to unit params
type PostConversionsFromUnitToUnitHandler interface {
	Handle(PostConversionsFromUnitToUnitParams, auth.Principal) PostConversionsFromUnitToUnitResponder
}

// NewPostConversionsFromUnitToUnit creates a new http.Handler for the post conversions from unit to unit operation
func NewPostConversionsFromUnitToUnit(ctx *middleware.Context, handler PostConversionsFromUnitToUnitHandler) *PostConversionsFromUnitToUnit {
	return &PostConversionsFromUnitToUnit{Context: ctx, Handler: handler}
}

/* PostConversionsFromUnitToUnit swagger:route POST /conversions/{fromUnit}/{toUnit} conversions postConversionsFromUnitToUnit

Creates add new conversion specification from unit to unit.

*/
type PostConversionsFromUnitToUnit struct {
	Context *middleware.Context
	Handler PostConversionsFromUnitToUnitHandler
}

func (o *PostConversionsFromUnitToUnit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConversionsFromUnitToUnitParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal auth.Principal
	if uprinc != nil {
		principal = uprinc.(auth.Principal) // this is really a auth.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
