// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// DeleteSeriesSeriesIDReader is a Reader for the DeleteSeriesSeriesID structure.
type DeleteSeriesSeriesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSeriesSeriesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSeriesSeriesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSeriesSeriesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteSeriesSeriesIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteSeriesSeriesIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSeriesSeriesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewDeleteSeriesSeriesIDMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSeriesSeriesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteSeriesSeriesIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSeriesSeriesIDNoContent creates a DeleteSeriesSeriesIDNoContent with default headers values
func NewDeleteSeriesSeriesIDNoContent() *DeleteSeriesSeriesIDNoContent {
	return &DeleteSeriesSeriesIDNoContent{}
}

/* DeleteSeriesSeriesIDNoContent describes a response with status code 204, with default header values.

Series successfully deleted.

*/
type DeleteSeriesSeriesIDNoContent struct {
}

// IsSuccess returns true when this delete series series Id no content response has a 2xx status code
func (o *DeleteSeriesSeriesIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete series series Id no content response has a 3xx status code
func (o *DeleteSeriesSeriesIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id no content response has a 4xx status code
func (o *DeleteSeriesSeriesIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete series series Id no content response has a 5xx status code
func (o *DeleteSeriesSeriesIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id no content response a status code equal to that given
func (o *DeleteSeriesSeriesIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteSeriesSeriesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdNoContent ", 204)
}

func (o *DeleteSeriesSeriesIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdNoContent ", 204)
}

func (o *DeleteSeriesSeriesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSeriesSeriesIDBadRequest creates a DeleteSeriesSeriesIDBadRequest with default headers values
func NewDeleteSeriesSeriesIDBadRequest() *DeleteSeriesSeriesIDBadRequest {
	return &DeleteSeriesSeriesIDBadRequest{}
}

/* DeleteSeriesSeriesIDBadRequest describes a response with status code 400, with default header values.

Client error in request. Input did not pass validations. See error details.

*/
type DeleteSeriesSeriesIDBadRequest struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete series series Id bad request response has a 2xx status code
func (o *DeleteSeriesSeriesIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id bad request response has a 3xx status code
func (o *DeleteSeriesSeriesIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id bad request response has a 4xx status code
func (o *DeleteSeriesSeriesIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete series series Id bad request response has a 5xx status code
func (o *DeleteSeriesSeriesIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id bad request response a status code equal to that given
func (o *DeleteSeriesSeriesIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteSeriesSeriesIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteSeriesSeriesIDBadRequest) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteSeriesSeriesIDBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSeriesSeriesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSeriesSeriesIDUnauthorized creates a DeleteSeriesSeriesIDUnauthorized with default headers values
func NewDeleteSeriesSeriesIDUnauthorized() *DeleteSeriesSeriesIDUnauthorized {
	return &DeleteSeriesSeriesIDUnauthorized{}
}

/* DeleteSeriesSeriesIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized access for a lack of authentication

*/
type DeleteSeriesSeriesIDUnauthorized struct {
}

// IsSuccess returns true when this delete series series Id unauthorized response has a 2xx status code
func (o *DeleteSeriesSeriesIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id unauthorized response has a 3xx status code
func (o *DeleteSeriesSeriesIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id unauthorized response has a 4xx status code
func (o *DeleteSeriesSeriesIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete series series Id unauthorized response has a 5xx status code
func (o *DeleteSeriesSeriesIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id unauthorized response a status code equal to that given
func (o *DeleteSeriesSeriesIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *DeleteSeriesSeriesIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdUnauthorized ", 401)
}

func (o *DeleteSeriesSeriesIDUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdUnauthorized ", 401)
}

func (o *DeleteSeriesSeriesIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSeriesSeriesIDForbidden creates a DeleteSeriesSeriesIDForbidden with default headers values
func NewDeleteSeriesSeriesIDForbidden() *DeleteSeriesSeriesIDForbidden {
	return &DeleteSeriesSeriesIDForbidden{}
}

/* DeleteSeriesSeriesIDForbidden describes a response with status code 403, with default header values.

Forbidden access for a lack of sufficient privileges

*/
type DeleteSeriesSeriesIDForbidden struct {
}

// IsSuccess returns true when this delete series series Id forbidden response has a 2xx status code
func (o *DeleteSeriesSeriesIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id forbidden response has a 3xx status code
func (o *DeleteSeriesSeriesIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id forbidden response has a 4xx status code
func (o *DeleteSeriesSeriesIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete series series Id forbidden response has a 5xx status code
func (o *DeleteSeriesSeriesIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id forbidden response a status code equal to that given
func (o *DeleteSeriesSeriesIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *DeleteSeriesSeriesIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdForbidden ", 403)
}

func (o *DeleteSeriesSeriesIDForbidden) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdForbidden ", 403)
}

func (o *DeleteSeriesSeriesIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSeriesSeriesIDNotFound creates a DeleteSeriesSeriesIDNotFound with default headers values
func NewDeleteSeriesSeriesIDNotFound() *DeleteSeriesSeriesIDNotFound {
	return &DeleteSeriesSeriesIDNotFound{}
}

/* DeleteSeriesSeriesIDNotFound describes a response with status code 404, with default header values.

Resource not found. The object requested does not exist or is not visible to the user.

*/
type DeleteSeriesSeriesIDNotFound struct {
}

// IsSuccess returns true when this delete series series Id not found response has a 2xx status code
func (o *DeleteSeriesSeriesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id not found response has a 3xx status code
func (o *DeleteSeriesSeriesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id not found response has a 4xx status code
func (o *DeleteSeriesSeriesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete series series Id not found response has a 5xx status code
func (o *DeleteSeriesSeriesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id not found response a status code equal to that given
func (o *DeleteSeriesSeriesIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteSeriesSeriesIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdNotFound ", 404)
}

func (o *DeleteSeriesSeriesIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdNotFound ", 404)
}

func (o *DeleteSeriesSeriesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSeriesSeriesIDMethodNotAllowed creates a DeleteSeriesSeriesIDMethodNotAllowed with default headers values
func NewDeleteSeriesSeriesIDMethodNotAllowed() *DeleteSeriesSeriesIDMethodNotAllowed {
	return &DeleteSeriesSeriesIDMethodNotAllowed{}
}

/* DeleteSeriesSeriesIDMethodNotAllowed describes a response with status code 405, with default header values.

MethodNotAllowed

*/
type DeleteSeriesSeriesIDMethodNotAllowed struct {
}

// IsSuccess returns true when this delete series series Id method not allowed response has a 2xx status code
func (o *DeleteSeriesSeriesIDMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id method not allowed response has a 3xx status code
func (o *DeleteSeriesSeriesIDMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id method not allowed response has a 4xx status code
func (o *DeleteSeriesSeriesIDMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete series series Id method not allowed response has a 5xx status code
func (o *DeleteSeriesSeriesIDMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this delete series series Id method not allowed response a status code equal to that given
func (o *DeleteSeriesSeriesIDMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *DeleteSeriesSeriesIDMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdMethodNotAllowed ", 405)
}

func (o *DeleteSeriesSeriesIDMethodNotAllowed) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdMethodNotAllowed ", 405)
}

func (o *DeleteSeriesSeriesIDMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSeriesSeriesIDInternalServerError creates a DeleteSeriesSeriesIDInternalServerError with default headers values
func NewDeleteSeriesSeriesIDInternalServerError() *DeleteSeriesSeriesIDInternalServerError {
	return &DeleteSeriesSeriesIDInternalServerError{}
}

/* DeleteSeriesSeriesIDInternalServerError describes a response with status code 500, with default header values.

An internal error has occured. See error details.

*/
type DeleteSeriesSeriesIDInternalServerError struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete series series Id internal server error response has a 2xx status code
func (o *DeleteSeriesSeriesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete series series Id internal server error response has a 3xx status code
func (o *DeleteSeriesSeriesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete series series Id internal server error response has a 4xx status code
func (o *DeleteSeriesSeriesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete series series Id internal server error response has a 5xx status code
func (o *DeleteSeriesSeriesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete series series Id internal server error response a status code equal to that given
func (o *DeleteSeriesSeriesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteSeriesSeriesIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSeriesSeriesIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] deleteSeriesSeriesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSeriesSeriesIDInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSeriesSeriesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSeriesSeriesIDDefault creates a DeleteSeriesSeriesIDDefault with default headers values
func NewDeleteSeriesSeriesIDDefault(code int) *DeleteSeriesSeriesIDDefault {
	return &DeleteSeriesSeriesIDDefault{
		_statusCode: code,
	}
}

/* DeleteSeriesSeriesIDDefault describes a response with status code -1, with default header values.

Other error. See error details.

*/
type DeleteSeriesSeriesIDDefault struct {
	_statusCode int

	Payload *models.APIError
}

// Code gets the status code for the delete series series ID default response
func (o *DeleteSeriesSeriesIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete series series ID default response has a 2xx status code
func (o *DeleteSeriesSeriesIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete series series ID default response has a 3xx status code
func (o *DeleteSeriesSeriesIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete series series ID default response has a 4xx status code
func (o *DeleteSeriesSeriesIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete series series ID default response has a 5xx status code
func (o *DeleteSeriesSeriesIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete series series ID default response a status code equal to that given
func (o *DeleteSeriesSeriesIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeleteSeriesSeriesIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] DeleteSeriesSeriesID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSeriesSeriesIDDefault) String() string {
	return fmt.Sprintf("[DELETE /series/{seriesId}][%d] DeleteSeriesSeriesID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSeriesSeriesIDDefault) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSeriesSeriesIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
