// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteSeriesSeriesIDParams creates a new DeleteSeriesSeriesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSeriesSeriesIDParams() *DeleteSeriesSeriesIDParams {
	return &DeleteSeriesSeriesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSeriesSeriesIDParamsWithTimeout creates a new DeleteSeriesSeriesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteSeriesSeriesIDParamsWithTimeout(timeout time.Duration) *DeleteSeriesSeriesIDParams {
	return &DeleteSeriesSeriesIDParams{
		timeout: timeout,
	}
}

// NewDeleteSeriesSeriesIDParamsWithContext creates a new DeleteSeriesSeriesIDParams object
// with the ability to set a context for a request.
func NewDeleteSeriesSeriesIDParamsWithContext(ctx context.Context) *DeleteSeriesSeriesIDParams {
	return &DeleteSeriesSeriesIDParams{
		Context: ctx,
	}
}

// NewDeleteSeriesSeriesIDParamsWithHTTPClient creates a new DeleteSeriesSeriesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSeriesSeriesIDParamsWithHTTPClient(client *http.Client) *DeleteSeriesSeriesIDParams {
	return &DeleteSeriesSeriesIDParams{
		HTTPClient: client,
	}
}

/* DeleteSeriesSeriesIDParams contains all the parameters to send to the API endpoint
   for the delete series series ID operation.

   Typically these are written to a http.Request.
*/
type DeleteSeriesSeriesIDParams struct {

	/* SeriesID.

	   The unique ID of a time series.

	   Format: int64
	*/
	SeriesID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete series series ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSeriesSeriesIDParams) WithDefaults() *DeleteSeriesSeriesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete series series ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSeriesSeriesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) WithTimeout(timeout time.Duration) *DeleteSeriesSeriesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) WithContext(ctx context.Context) *DeleteSeriesSeriesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) WithHTTPClient(client *http.Client) *DeleteSeriesSeriesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSeriesID adds the seriesID to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) WithSeriesID(seriesID int64) *DeleteSeriesSeriesIDParams {
	o.SetSeriesID(seriesID)
	return o
}

// SetSeriesID adds the seriesId to the delete series series ID params
func (o *DeleteSeriesSeriesIDParams) SetSeriesID(seriesID int64) {
	o.SeriesID = seriesID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSeriesSeriesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param seriesId
	if err := r.SetPathParam("seriesId", swag.FormatInt64(o.SeriesID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
