// Code generated by go-swagger; DO NOT EDIT.

package series

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// NewPutSeriesVersionsVersionedSeriesIDValuesParams creates a new PutSeriesVersionsVersionedSeriesIDValuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSeriesVersionsVersionedSeriesIDValuesParams() *PutSeriesVersionsVersionedSeriesIDValuesParams {
	return &PutSeriesVersionsVersionedSeriesIDValuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithTimeout creates a new PutSeriesVersionsVersionedSeriesIDValuesParams object
// with the ability to set a timeout on a request.
func NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithTimeout(timeout time.Duration) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	return &PutSeriesVersionsVersionedSeriesIDValuesParams{
		timeout: timeout,
	}
}

// NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithContext creates a new PutSeriesVersionsVersionedSeriesIDValuesParams object
// with the ability to set a context for a request.
func NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithContext(ctx context.Context) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	return &PutSeriesVersionsVersionedSeriesIDValuesParams{
		Context: ctx,
	}
}

// NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithHTTPClient creates a new PutSeriesVersionsVersionedSeriesIDValuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSeriesVersionsVersionedSeriesIDValuesParamsWithHTTPClient(client *http.Client) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	return &PutSeriesVersionsVersionedSeriesIDValuesParams{
		HTTPClient: client,
	}
}

/* PutSeriesVersionsVersionedSeriesIDValuesParams contains all the parameters to send to the API endpoint
   for the put series versions versioned series ID values operation.

   Typically these are written to a http.Request.
*/
type PutSeriesVersionsVersionedSeriesIDValuesParams struct {

	/* Values.

	   The values of a time series

	*/
	Values models.TsValues

	/* VersionedSeriesID.

	   The UUID of a version of the time series.

	   Format: uuid
	*/
	VersionedSeriesID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put series versions versioned series ID values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithDefaults() *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put series versions versioned series ID values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithTimeout(timeout time.Duration) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithContext(ctx context.Context) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithHTTPClient(client *http.Client) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithValues adds the values to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithValues(values models.TsValues) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetValues(values)
	return o
}

// SetValues adds the values to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetValues(values models.TsValues) {
	o.Values = values
}

// WithVersionedSeriesID adds the versionedSeriesID to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WithVersionedSeriesID(versionedSeriesID strfmt.UUID) *PutSeriesVersionsVersionedSeriesIDValuesParams {
	o.SetVersionedSeriesID(versionedSeriesID)
	return o
}

// SetVersionedSeriesID adds the versionedSeriesId to the put series versions versioned series ID values params
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) SetVersionedSeriesID(versionedSeriesID strfmt.UUID) {
	o.VersionedSeriesID = versionedSeriesID
}

// WriteToRequest writes these params to a swagger request
func (o *PutSeriesVersionsVersionedSeriesIDValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Values != nil {
		if err := r.SetBodyParam(o.Values); err != nil {
			return err
		}
	}

	// path param versionedSeriesId
	if err := r.SetPathParam("versionedSeriesId", o.VersionedSeriesID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
