// Code generated by go-swagger; DO NOT EDIT.

package classes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetClassesClassIDMembersURL generates an URL for the get classes class ID members operation
type GetClassesClassIDMembersURL struct {
	ClassID string

	Audit *bool
	Brief *bool
	Deep  *bool
	Glob  *string
	Tag   *string
	Tags  []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClassesClassIDMembersURL) WithBasePath(bp string) *GetClassesClassIDMembersURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetClassesClassIDMembersURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetClassesClassIDMembersURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/classes/{classId}/members"

	classID := o.ClassID
	if classID != "" {
		_path = strings.Replace(_path, "{classId}", classID, -1)
	} else {
		return nil, errors.New("classId is required on GetClassesClassIDMembersURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var auditQ string
	if o.Audit != nil {
		auditQ = swag.FormatBool(*o.Audit)
	}
	if auditQ != "" {
		qs.Set("audit", auditQ)
	}

	var briefQ string
	if o.Brief != nil {
		briefQ = swag.FormatBool(*o.Brief)
	}
	if briefQ != "" {
		qs.Set("brief", briefQ)
	}

	var deepQ string
	if o.Deep != nil {
		deepQ = swag.FormatBool(*o.Deep)
	}
	if deepQ != "" {
		qs.Set("deep", deepQ)
	}

	var globQ string
	if o.Glob != nil {
		globQ = *o.Glob
	}
	if globQ != "" {
		qs.Set("glob", globQ)
	}

	var tagQ string
	if o.Tag != nil {
		tagQ = *o.Tag
	}
	if tagQ != "" {
		qs.Set("tag", tagQ)
	}

	var tagsIR []string
	for _, tagsI := range o.Tags {
		tagsIS := tagsI
		if tagsIS != "" {
			tagsIR = append(tagsIR, tagsIS)
		}
	}

	tags := swag.JoinByFormat(tagsIR, "csv")

	if len(tags) > 0 {
		qsv := tags[0]
		if qsv != "" {
			qs.Set("tags", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetClassesClassIDMembersURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetClassesClassIDMembersURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetClassesClassIDMembersURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetClassesClassIDMembersURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetClassesClassIDMembersURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetClassesClassIDMembersURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
