// Code generated by go-swagger; DO NOT EDIT.

package classes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetClassesParams creates a new GetClassesParams object
//
// There are no default values defined in the spec.
func NewGetClassesParams() GetClassesParams {

	return GetClassesParams{}
}

// GetClassesParams contains all the bound params for the get classes operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetClasses
type GetClassesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*When audit is specified, the response will also contain the audit trail field.

	  In: query
	*/
	Audit *bool
	/*When brief is specified, the response will only contain essential data and strip long descriptions.

	  In: query
	*/
	Brief *bool
	/*When deep is specified, the response will contain a deep representation of the object, rather than just a shallow description.

	  In: query
	*/
	Deep *bool
	/*Filters the result according to a glob pattern applied on the short name of the requested object.

	  Max Length: 100
	  Min Length: 1
	  In: query
	*/
	Glob *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClassesParams() beforehand.
func (o *GetClassesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAudit, qhkAudit, _ := qs.GetOK("audit")
	if err := o.bindAudit(qAudit, qhkAudit, route.Formats); err != nil {
		res = append(res, err)
	}

	qBrief, qhkBrief, _ := qs.GetOK("brief")
	if err := o.bindBrief(qBrief, qhkBrief, route.Formats); err != nil {
		res = append(res, err)
	}

	qDeep, qhkDeep, _ := qs.GetOK("deep")
	if err := o.bindDeep(qDeep, qhkDeep, route.Formats); err != nil {
		res = append(res, err)
	}

	qGlob, qhkGlob, _ := qs.GetOK("glob")
	if err := o.bindGlob(qGlob, qhkGlob, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAudit binds and validates parameter Audit from query.
func (o *GetClassesParams) bindAudit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("audit", "query", "bool", raw)
	}
	o.Audit = &value

	return nil
}

// bindBrief binds and validates parameter Brief from query.
func (o *GetClassesParams) bindBrief(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("brief", "query", "bool", raw)
	}
	o.Brief = &value

	return nil
}

// bindDeep binds and validates parameter Deep from query.
func (o *GetClassesParams) bindDeep(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("deep", "query", "bool", raw)
	}
	o.Deep = &value

	return nil
}

// bindGlob binds and validates parameter Glob from query.
func (o *GetClassesParams) bindGlob(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Glob = &raw

	if err := o.validateGlob(formats); err != nil {
		return err
	}

	return nil
}

// validateGlob carries on validations for parameter Glob
func (o *GetClassesParams) validateGlob(formats strfmt.Registry) error {

	if err := validate.MinLength("glob", "query", *o.Glob, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("glob", "query", *o.Glob, 100); err != nil {
		return err
	}

	return nil
}
