# Climate time series API
#
# The API allows the public to search and consult time series about climate change research conducted by TheShiftProject.  The climate time series API allows contributors to upload time series about their climate change models and studies.  Other secured endpoints allows admins to maintain the nomenclatures used by the climate time series, such as units etc. Timeseries publication status and ownership is for now managed by admins. 
#
# OpenAPI spec version: v0.0.1
# Contact: fredbi@yahoo.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Constant Class
#'
#' @field id 
#' @field shortCode 
#' @field title 
#' @field descriptionShort 
#' @field descriptionLong 
#' @field auditTrail 
#' @field symbol 
#' @field value 
#' @field metadata 
#' @field measurementUnit 
#' @field constantHasMeasurementDomains 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Constant <- R6::R6Class(
  'Constant',
  public = list(
    `id` = NULL,
    `shortCode` = NULL,
    `title` = NULL,
    `descriptionShort` = NULL,
    `descriptionLong` = NULL,
    `auditTrail` = NULL,
    `symbol` = NULL,
    `value` = NULL,
    `metadata` = NULL,
    `measurementUnit` = NULL,
    `constantHasMeasurementDomains` = NULL,
    initialize = function(`id`, `shortCode`, `title`, `descriptionShort`, `descriptionLong`, `auditTrail`, `symbol`, `value`, `metadata`, `measurementUnit`, `constantHasMeasurementDomains`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`shortCode`)) {
        stopifnot(R6::is.R6(`shortCode`))
        self$`shortCode` <- `shortCode`
      }
      if (!missing(`title`)) {
        stopifnot(R6::is.R6(`title`))
        self$`title` <- `title`
      }
      if (!missing(`descriptionShort`)) {
        stopifnot(R6::is.R6(`descriptionShort`))
        self$`descriptionShort` <- `descriptionShort`
      }
      if (!missing(`descriptionLong`)) {
        stopifnot(R6::is.R6(`descriptionLong`))
        self$`descriptionLong` <- `descriptionLong`
      }
      if (!missing(`auditTrail`)) {
        stopifnot(R6::is.R6(`auditTrail`))
        self$`auditTrail` <- `auditTrail`
      }
      if (!missing(`symbol`)) {
        stopifnot(is.character(`symbol`), length(`symbol`) == 1)
        self$`symbol` <- `symbol`
      }
      if (!missing(`value`)) {
        stopifnot(is.numeric(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
      if (!missing(`metadata`)) {
        stopifnot(R6::is.R6(`metadata`))
        self$`metadata` <- `metadata`
      }
      if (!missing(`measurementUnit`)) {
        stopifnot(R6::is.R6(`measurementUnit`))
        self$`measurementUnit` <- `measurementUnit`
      }
      if (!missing(`constantHasMeasurementDomains`)) {
        stopifnot(is.list(`constantHasMeasurementDomains`), length(`constantHasMeasurementDomains`) != 0)
        lapply(`constantHasMeasurementDomains`, function(x) stopifnot(R6::is.R6(x)))
        self$`constantHasMeasurementDomains` <- `constantHasMeasurementDomains`
      }
    },
    toJSON = function() {
      ConstantObject <- list()
      if (!is.null(self$`id`)) {
        ConstantObject[['id']] <- self$`id`
      }
      if (!is.null(self$`shortCode`)) {
        ConstantObject[['shortCode']] <- self$`shortCode`$toJSON()
      }
      if (!is.null(self$`title`)) {
        ConstantObject[['title']] <- self$`title`$toJSON()
      }
      if (!is.null(self$`descriptionShort`)) {
        ConstantObject[['descriptionShort']] <- self$`descriptionShort`$toJSON()
      }
      if (!is.null(self$`descriptionLong`)) {
        ConstantObject[['descriptionLong']] <- self$`descriptionLong`$toJSON()
      }
      if (!is.null(self$`auditTrail`)) {
        ConstantObject[['auditTrail']] <- self$`auditTrail`$toJSON()
      }
      if (!is.null(self$`symbol`)) {
        ConstantObject[['symbol']] <- self$`symbol`
      }
      if (!is.null(self$`value`)) {
        ConstantObject[['value']] <- self$`value`
      }
      if (!is.null(self$`metadata`)) {
        ConstantObject[['metadata']] <- self$`metadata`$toJSON()
      }
      if (!is.null(self$`measurementUnit`)) {
        ConstantObject[['measurementUnit']] <- self$`measurementUnit`$toJSON()
      }
      if (!is.null(self$`constantHasMeasurementDomains`)) {
        ConstantObject[['constantHasMeasurementDomains']] <- lapply(self$`constantHasMeasurementDomains`, function(x) x$toJSON())
      }

      ConstantObject
    },
    fromJSON = function(ConstantJson) {
      ConstantObject <- jsonlite::fromJSON(ConstantJson)
      if (!is.null(ConstantObject$`id`)) {
        self$`id` <- ConstantObject$`id`
      }
      if (!is.null(ConstantObject$`shortCode`)) {
        shortCodeObject <- ClassNomenclatureName$new()
        shortCodeObject$fromJSON(jsonlite::toJSON(ConstantObject$shortCode, auto_unbox = TRUE))
        self$`shortCode` <- shortCodeObject
      }
      if (!is.null(ConstantObject$`title`)) {
        titleObject <- Translation$new()
        titleObject$fromJSON(jsonlite::toJSON(ConstantObject$title, auto_unbox = TRUE))
        self$`title` <- titleObject
      }
      if (!is.null(ConstantObject$`descriptionShort`)) {
        descriptionShortObject <- Translation$new()
        descriptionShortObject$fromJSON(jsonlite::toJSON(ConstantObject$descriptionShort, auto_unbox = TRUE))
        self$`descriptionShort` <- descriptionShortObject
      }
      if (!is.null(ConstantObject$`descriptionLong`)) {
        descriptionLongObject <- Translation$new()
        descriptionLongObject$fromJSON(jsonlite::toJSON(ConstantObject$descriptionLong, auto_unbox = TRUE))
        self$`descriptionLong` <- descriptionLongObject
      }
      if (!is.null(ConstantObject$`auditTrail`)) {
        auditTrailObject <- Audit$new()
        auditTrailObject$fromJSON(jsonlite::toJSON(ConstantObject$auditTrail, auto_unbox = TRUE))
        self$`auditTrail` <- auditTrailObject
      }
      if (!is.null(ConstantObject$`symbol`)) {
        self$`symbol` <- ConstantObject$`symbol`
      }
      if (!is.null(ConstantObject$`value`)) {
        self$`value` <- ConstantObject$`value`
      }
      if (!is.null(ConstantObject$`metadata`)) {
        metadataObject <- Mumeta$new()
        metadataObject$fromJSON(jsonlite::toJSON(ConstantObject$metadata, auto_unbox = TRUE))
        self$`metadata` <- metadataObject
      }
      if (!is.null(ConstantObject$`measurementUnit`)) {
        measurementUnitObject <- Munit$new()
        measurementUnitObject$fromJSON(jsonlite::toJSON(ConstantObject$measurementUnit, auto_unbox = TRUE))
        self$`measurementUnit` <- measurementUnitObject
      }
      if (!is.null(ConstantObject$`constantHasMeasurementDomains`)) {
        self$`constantHasMeasurementDomains` <- lapply(ConstantObject$`constantHasMeasurementDomains`, function(x) {
          constantHasMeasurementDomainsObject <- Mdomain$new()
          constantHasMeasurementDomainsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          constantHasMeasurementDomainsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "shortCode": %s,
           "title": %s,
           "descriptionShort": %s,
           "descriptionLong": %s,
           "auditTrail": %s,
           "symbol": %s,
           "value": %d,
           "metadata": %s,
           "measurementUnit": %s,
           "constantHasMeasurementDomains": [%s]
        }',
        self$`id`,
        self$`shortCode`$toJSON(),
        self$`title`$toJSON(),
        self$`descriptionShort`$toJSON(),
        self$`descriptionLong`$toJSON(),
        self$`auditTrail`$toJSON(),
        self$`symbol`,
        self$`value`,
        self$`metadata`$toJSON(),
        self$`measurementUnit`$toJSON(),
        lapply(self$`constantHasMeasurementDomains`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ConstantJson) {
      ConstantObject <- jsonlite::fromJSON(ConstantJson)
      self$`id` <- ConstantObject$`id`
      ClassNomenclatureNameObject <- ClassNomenclatureName$new()
      self$`shortCode` <- ClassNomenclatureNameObject$fromJSON(jsonlite::toJSON(ConstantObject$shortCode, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`title` <- TranslationObject$fromJSON(jsonlite::toJSON(ConstantObject$title, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`descriptionShort` <- TranslationObject$fromJSON(jsonlite::toJSON(ConstantObject$descriptionShort, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`descriptionLong` <- TranslationObject$fromJSON(jsonlite::toJSON(ConstantObject$descriptionLong, auto_unbox = TRUE))
      AuditObject <- Audit$new()
      self$`auditTrail` <- AuditObject$fromJSON(jsonlite::toJSON(ConstantObject$auditTrail, auto_unbox = TRUE))
      self$`symbol` <- ConstantObject$`symbol`
      self$`value` <- ConstantObject$`value`
      MumetaObject <- Mumeta$new()
      self$`metadata` <- MumetaObject$fromJSON(jsonlite::toJSON(ConstantObject$metadata, auto_unbox = TRUE))
      MunitObject <- Munit$new()
      self$`measurementUnit` <- MunitObject$fromJSON(jsonlite::toJSON(ConstantObject$measurementUnit, auto_unbox = TRUE))
      self$`constantHasMeasurementDomains` <- lapply(ConstantObject$`constantHasMeasurementDomains`, function(x) Mdomain$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
