# Climate time series API
#
# The API allows the public to search and consult time series about climate change research conducted by TheShiftProject.  The climate time series API allows contributors to upload time series about their climate change models and studies.  Other secured endpoints allows admins to maintain the nomenclatures used by the climate time series, such as units etc. Timeseries publication status and ownership is for now managed by admins. 
#
# OpenAPI spec version: v0.0.1
# Contact: fredbi@yahoo.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Munit Class
#'
#' @field id 
#' @field shortCode 
#' @field title 
#' @field descriptionShort 
#' @field descriptionLong 
#' @field auditTrail 
#' @field isStandard 
#' @field includedMultiplier 
#' @field unitMeasurement 
#' @field unitMeasurementSystem 
#' @field metadata 
#' @field measurementUnitHasConversions 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Munit <- R6::R6Class(
  'Munit',
  public = list(
    `id` = NULL,
    `shortCode` = NULL,
    `title` = NULL,
    `descriptionShort` = NULL,
    `descriptionLong` = NULL,
    `auditTrail` = NULL,
    `isStandard` = NULL,
    `includedMultiplier` = NULL,
    `unitMeasurement` = NULL,
    `unitMeasurementSystem` = NULL,
    `metadata` = NULL,
    `measurementUnitHasConversions` = NULL,
    initialize = function(`id`, `shortCode`, `title`, `descriptionShort`, `descriptionLong`, `auditTrail`, `isStandard`, `includedMultiplier`, `unitMeasurement`, `unitMeasurementSystem`, `metadata`, `measurementUnitHasConversions`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`shortCode`)) {
        stopifnot(R6::is.R6(`shortCode`))
        self$`shortCode` <- `shortCode`
      }
      if (!missing(`title`)) {
        stopifnot(R6::is.R6(`title`))
        self$`title` <- `title`
      }
      if (!missing(`descriptionShort`)) {
        stopifnot(R6::is.R6(`descriptionShort`))
        self$`descriptionShort` <- `descriptionShort`
      }
      if (!missing(`descriptionLong`)) {
        stopifnot(R6::is.R6(`descriptionLong`))
        self$`descriptionLong` <- `descriptionLong`
      }
      if (!missing(`auditTrail`)) {
        stopifnot(R6::is.R6(`auditTrail`))
        self$`auditTrail` <- `auditTrail`
      }
      if (!missing(`isStandard`)) {
        self$`isStandard` <- `isStandard`
      }
      if (!missing(`includedMultiplier`)) {
        stopifnot(R6::is.R6(`includedMultiplier`))
        self$`includedMultiplier` <- `includedMultiplier`
      }
      if (!missing(`unitMeasurement`)) {
        stopifnot(R6::is.R6(`unitMeasurement`))
        self$`unitMeasurement` <- `unitMeasurement`
      }
      if (!missing(`unitMeasurementSystem`)) {
        stopifnot(R6::is.R6(`unitMeasurementSystem`))
        self$`unitMeasurementSystem` <- `unitMeasurementSystem`
      }
      if (!missing(`metadata`)) {
        stopifnot(R6::is.R6(`metadata`))
        self$`metadata` <- `metadata`
      }
      if (!missing(`measurementUnitHasConversions`)) {
        stopifnot(is.list(`measurementUnitHasConversions`), length(`measurementUnitHasConversions`) != 0)
        lapply(`measurementUnitHasConversions`, function(x) stopifnot(R6::is.R6(x)))
        self$`measurementUnitHasConversions` <- `measurementUnitHasConversions`
      }
    },
    toJSON = function() {
      MunitObject <- list()
      if (!is.null(self$`id`)) {
        MunitObject[['id']] <- self$`id`
      }
      if (!is.null(self$`shortCode`)) {
        MunitObject[['shortCode']] <- self$`shortCode`$toJSON()
      }
      if (!is.null(self$`title`)) {
        MunitObject[['title']] <- self$`title`$toJSON()
      }
      if (!is.null(self$`descriptionShort`)) {
        MunitObject[['descriptionShort']] <- self$`descriptionShort`$toJSON()
      }
      if (!is.null(self$`descriptionLong`)) {
        MunitObject[['descriptionLong']] <- self$`descriptionLong`$toJSON()
      }
      if (!is.null(self$`auditTrail`)) {
        MunitObject[['auditTrail']] <- self$`auditTrail`$toJSON()
      }
      if (!is.null(self$`isStandard`)) {
        MunitObject[['isStandard']] <- self$`isStandard`
      }
      if (!is.null(self$`includedMultiplier`)) {
        MunitObject[['includedMultiplier']] <- self$`includedMultiplier`$toJSON()
      }
      if (!is.null(self$`unitMeasurement`)) {
        MunitObject[['unitMeasurement']] <- self$`unitMeasurement`$toJSON()
      }
      if (!is.null(self$`unitMeasurementSystem`)) {
        MunitObject[['unitMeasurementSystem']] <- self$`unitMeasurementSystem`$toJSON()
      }
      if (!is.null(self$`metadata`)) {
        MunitObject[['metadata']] <- self$`metadata`$toJSON()
      }
      if (!is.null(self$`measurementUnitHasConversions`)) {
        MunitObject[['measurementUnitHasConversions']] <- lapply(self$`measurementUnitHasConversions`, function(x) x$toJSON())
      }

      MunitObject
    },
    fromJSON = function(MunitJson) {
      MunitObject <- jsonlite::fromJSON(MunitJson)
      if (!is.null(MunitObject$`id`)) {
        self$`id` <- MunitObject$`id`
      }
      if (!is.null(MunitObject$`shortCode`)) {
        shortCodeObject <- ClassNomenclatureName$new()
        shortCodeObject$fromJSON(jsonlite::toJSON(MunitObject$shortCode, auto_unbox = TRUE))
        self$`shortCode` <- shortCodeObject
      }
      if (!is.null(MunitObject$`title`)) {
        titleObject <- Translation$new()
        titleObject$fromJSON(jsonlite::toJSON(MunitObject$title, auto_unbox = TRUE))
        self$`title` <- titleObject
      }
      if (!is.null(MunitObject$`descriptionShort`)) {
        descriptionShortObject <- Translation$new()
        descriptionShortObject$fromJSON(jsonlite::toJSON(MunitObject$descriptionShort, auto_unbox = TRUE))
        self$`descriptionShort` <- descriptionShortObject
      }
      if (!is.null(MunitObject$`descriptionLong`)) {
        descriptionLongObject <- Translation$new()
        descriptionLongObject$fromJSON(jsonlite::toJSON(MunitObject$descriptionLong, auto_unbox = TRUE))
        self$`descriptionLong` <- descriptionLongObject
      }
      if (!is.null(MunitObject$`auditTrail`)) {
        auditTrailObject <- Audit$new()
        auditTrailObject$fromJSON(jsonlite::toJSON(MunitObject$auditTrail, auto_unbox = TRUE))
        self$`auditTrail` <- auditTrailObject
      }
      if (!is.null(MunitObject$`isStandard`)) {
        self$`isStandard` <- MunitObject$`isStandard`
      }
      if (!is.null(MunitObject$`includedMultiplier`)) {
        includedMultiplierObject <- Multiplier$new()
        includedMultiplierObject$fromJSON(jsonlite::toJSON(MunitObject$includedMultiplier, auto_unbox = TRUE))
        self$`includedMultiplier` <- includedMultiplierObject
      }
      if (!is.null(MunitObject$`unitMeasurement`)) {
        unitMeasurementObject <- Measurement$new()
        unitMeasurementObject$fromJSON(jsonlite::toJSON(MunitObject$unitMeasurement, auto_unbox = TRUE))
        self$`unitMeasurement` <- unitMeasurementObject
      }
      if (!is.null(MunitObject$`unitMeasurementSystem`)) {
        unitMeasurementSystemObject <- Musystem$new()
        unitMeasurementSystemObject$fromJSON(jsonlite::toJSON(MunitObject$unitMeasurementSystem, auto_unbox = TRUE))
        self$`unitMeasurementSystem` <- unitMeasurementSystemObject
      }
      if (!is.null(MunitObject$`metadata`)) {
        metadataObject <- Mumeta$new()
        metadataObject$fromJSON(jsonlite::toJSON(MunitObject$metadata, auto_unbox = TRUE))
        self$`metadata` <- metadataObject
      }
      if (!is.null(MunitObject$`measurementUnitHasConversions`)) {
        self$`measurementUnitHasConversions` <- lapply(MunitObject$`measurementUnitHasConversions`, function(x) {
          measurementUnitHasConversionsObject <- ConversionSpec$new()
          measurementUnitHasConversionsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          measurementUnitHasConversionsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "shortCode": %s,
           "title": %s,
           "descriptionShort": %s,
           "descriptionLong": %s,
           "auditTrail": %s,
           "isStandard": %s,
           "includedMultiplier": %s,
           "unitMeasurement": %s,
           "unitMeasurementSystem": %s,
           "metadata": %s,
           "measurementUnitHasConversions": [%s]
        }',
        self$`id`,
        self$`shortCode`$toJSON(),
        self$`title`$toJSON(),
        self$`descriptionShort`$toJSON(),
        self$`descriptionLong`$toJSON(),
        self$`auditTrail`$toJSON(),
        self$`isStandard`,
        self$`includedMultiplier`$toJSON(),
        self$`unitMeasurement`$toJSON(),
        self$`unitMeasurementSystem`$toJSON(),
        self$`metadata`$toJSON(),
        lapply(self$`measurementUnitHasConversions`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(MunitJson) {
      MunitObject <- jsonlite::fromJSON(MunitJson)
      self$`id` <- MunitObject$`id`
      ClassNomenclatureNameObject <- ClassNomenclatureName$new()
      self$`shortCode` <- ClassNomenclatureNameObject$fromJSON(jsonlite::toJSON(MunitObject$shortCode, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`title` <- TranslationObject$fromJSON(jsonlite::toJSON(MunitObject$title, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`descriptionShort` <- TranslationObject$fromJSON(jsonlite::toJSON(MunitObject$descriptionShort, auto_unbox = TRUE))
      TranslationObject <- Translation$new()
      self$`descriptionLong` <- TranslationObject$fromJSON(jsonlite::toJSON(MunitObject$descriptionLong, auto_unbox = TRUE))
      AuditObject <- Audit$new()
      self$`auditTrail` <- AuditObject$fromJSON(jsonlite::toJSON(MunitObject$auditTrail, auto_unbox = TRUE))
      self$`isStandard` <- MunitObject$`isStandard`
      MultiplierObject <- Multiplier$new()
      self$`includedMultiplier` <- MultiplierObject$fromJSON(jsonlite::toJSON(MunitObject$includedMultiplier, auto_unbox = TRUE))
      MeasurementObject <- Measurement$new()
      self$`unitMeasurement` <- MeasurementObject$fromJSON(jsonlite::toJSON(MunitObject$unitMeasurement, auto_unbox = TRUE))
      MusystemObject <- Musystem$new()
      self$`unitMeasurementSystem` <- MusystemObject$fromJSON(jsonlite::toJSON(MunitObject$unitMeasurementSystem, auto_unbox = TRUE))
      MumetaObject <- Mumeta$new()
      self$`metadata` <- MumetaObject$fromJSON(jsonlite::toJSON(MunitObject$metadata, auto_unbox = TRUE))
      self$`measurementUnitHasConversions` <- lapply(MunitObject$`measurementUnitHasConversions`, function(x) ConversionSpec$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
