// Code generated by go-swagger; DO NOT EDIT.

package conversions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fredbi/climate-timeseries/pkg/restapi/models"
)

// NewPostConversionsFromUnitToUnitParams creates a new PostConversionsFromUnitToUnitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostConversionsFromUnitToUnitParams() *PostConversionsFromUnitToUnitParams {
	return &PostConversionsFromUnitToUnitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostConversionsFromUnitToUnitParamsWithTimeout creates a new PostConversionsFromUnitToUnitParams object
// with the ability to set a timeout on a request.
func NewPostConversionsFromUnitToUnitParamsWithTimeout(timeout time.Duration) *PostConversionsFromUnitToUnitParams {
	return &PostConversionsFromUnitToUnitParams{
		timeout: timeout,
	}
}

// NewPostConversionsFromUnitToUnitParamsWithContext creates a new PostConversionsFromUnitToUnitParams object
// with the ability to set a context for a request.
func NewPostConversionsFromUnitToUnitParamsWithContext(ctx context.Context) *PostConversionsFromUnitToUnitParams {
	return &PostConversionsFromUnitToUnitParams{
		Context: ctx,
	}
}

// NewPostConversionsFromUnitToUnitParamsWithHTTPClient creates a new PostConversionsFromUnitToUnitParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostConversionsFromUnitToUnitParamsWithHTTPClient(client *http.Client) *PostConversionsFromUnitToUnitParams {
	return &PostConversionsFromUnitToUnitParams{
		HTTPClient: client,
	}
}

/* PostConversionsFromUnitToUnitParams contains all the parameters to send to the API endpoint
   for the post conversions from unit to unit operation.

   Typically these are written to a http.Request.
*/
type PostConversionsFromUnitToUnitParams struct {

	/* ConversionSpec.

	   Unit conversion specification.

	*/
	ConversionSpec models.ConversionSpec

	/* FromUnit.

	   Original unit to be converted.

	*/
	FromUnit string

	/* ToUnit.

	   Original unit to be converted.

	*/
	ToUnit string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post conversions from unit to unit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostConversionsFromUnitToUnitParams) WithDefaults() *PostConversionsFromUnitToUnitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post conversions from unit to unit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostConversionsFromUnitToUnitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithTimeout(timeout time.Duration) *PostConversionsFromUnitToUnitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithContext(ctx context.Context) *PostConversionsFromUnitToUnitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithHTTPClient(client *http.Client) *PostConversionsFromUnitToUnitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConversionSpec adds the conversionSpec to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithConversionSpec(conversionSpec models.ConversionSpec) *PostConversionsFromUnitToUnitParams {
	o.SetConversionSpec(conversionSpec)
	return o
}

// SetConversionSpec adds the conversionSpec to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetConversionSpec(conversionSpec models.ConversionSpec) {
	o.ConversionSpec = conversionSpec
}

// WithFromUnit adds the fromUnit to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithFromUnit(fromUnit string) *PostConversionsFromUnitToUnitParams {
	o.SetFromUnit(fromUnit)
	return o
}

// SetFromUnit adds the fromUnit to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetFromUnit(fromUnit string) {
	o.FromUnit = fromUnit
}

// WithToUnit adds the toUnit to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) WithToUnit(toUnit string) *PostConversionsFromUnitToUnitParams {
	o.SetToUnit(toUnit)
	return o
}

// SetToUnit adds the toUnit to the post conversions from unit to unit params
func (o *PostConversionsFromUnitToUnitParams) SetToUnit(toUnit string) {
	o.ToUnit = toUnit
}

// WriteToRequest writes these params to a swagger request
func (o *PostConversionsFromUnitToUnitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.ConversionSpec); err != nil {
		return err
	}

	// path param fromUnit
	if err := r.SetPathParam("fromUnit", o.FromUnit); err != nil {
		return err
	}

	// path param toUnit
	if err := r.SetPathParam("toUnit", o.ToUnit); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
